# Generated by Django 2.0.1 on 2018-05-10 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Member')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('image_promotion', models.ImageField(upload_to='Promotion')),
                ('type_promotion', models.CharField(choices=[('N', 'Normally'), ('P', 'Promotion(1 Free 1)')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='interest',
            name='matching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='divvy.Member'),
        ),
        migrations.AddField(
            model_name='interest',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matcher', to='divvy.Member'),
        ),
        migrations.AddField(
            model_name='interest',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divvy.Promotion'),
        ),
    ]
