# Generated by Django 2.0.1 on 2018-04-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divvy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
