# Generated by Django 2.0.1 on 2018-05-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divvy', '0002_auto_20180511_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
