# Generated by Django 2.0.1 on 2018-05-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divvy', '0003_auto_20180513_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='matching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='divvy.Member'),
        ),
    ]
